version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/src

  # frontend:
  #   build:
  #     dockerfile: Dockerfile.dev
  #   environment:
  #     - NODE_ENV=development
  #     - REACT_APP_KEYCLOAK_URL=http://localhost:8080/
  #     - REACT_APP_KEYCLOAK_REALM=student-realm
  #     - REACT_APP_KEYCLOAK_CLIENT_ID=student-client
  #     - REACT_APP_BACKEND_URL=http://localhost:5000/api
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
