version: '3.8'

networks:
  keycloak-network:

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command:
      - start-dev
    networks:
      - keycloak-network

  mariadb-primary:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: studentdb
      MYSQL_USER: bob4o
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - keycloak-network

  mariadb-secondary:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: studentdb
      MYSQL_USER: bob4o
      MYSQL_PASSWORD: admin
    networks:
      - keycloak-network

  maxscale:
    image: mariadb/maxscale:latest
    environment:
      MAXSCALE_USER: maxscale
      MAXSCALE_PASSWORD: maxscale
    ports:
      - "4006:4006"
    volumes:
      - ./maxscale.cnf:/etc/maxscale.cnf
    networks:
      - keycloak-network
    depends_on:
      - mariadb-primary
      - mariadb-secondary

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=maxscale;Database=studentdb;User=bob4o;Password=admin;
      - Keycloak__Authority=http://keycloak:8080/auth/realms/student-realm
      - Keycloak__ClientId=student-client
    depends_on:
      - maxscale
      - keycloak
    ports:
      - "5000:5000"
    networks:
      - keycloak-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - REACT_APP_KEYCLOAK_URL=http://localhost:8080/
      - REACT_APP_KEYCLOAK_REALM=student-realm
      - REACT_APP_KEYCLOAK_CLIENT_ID=student-client
      - REACT_APP_BACKEND_URL=http://localhost:5000/api
    ports:
      - "80:80"
    depends_on:
      - keycloak
    networks:
      - keycloak-network
